### ISSUE TITLE
Upgrade to 2.93?

### ISSUE THREAD

**Issue by bn326160** [jaymoulin/docker-transmission#4]
Some trackers deny connection with transmission 2.92, is it possible to upgrade the deamon?

**Comment by bn326160** [comment]
Sorry I'm new to Docker. Was able to figure out the container runs Alpine Linux.

I was able to add "http://dl-4.alpinelinux.org/alpine/edge/main/" to the repositories, which contains 2.93.

**Comment by jaymoulin** [comment]
https://github.com/jaymoulin/docker-transmission/issues/2 is supposed to do it automatically. I'll check what happens
